config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'images#featured'

  get '/admin', to: 'site#admin'
  post '/admin', to: 'site#admin'

  get '/fcadmin', to: 'site#fcadmin'

  get '/login', to: 'site#login'
  get '/logout', to: 'site#logout'

  post '/authors/:id/edit', to: 'authors#edit'
  post '/topics/:id/edit', to: 'topics#edit'
  post '/featured_collections/:id/edit', to: 'featured_collections#edit'
  post '/regions/:id/edit', to: 'regions#edit'
  post '/cal_standards/:id/edit', to: 'cal_standards#edit'
  post '/nat_standards/:id/edit', to: 'nat_standards#edit'

  # get '/images/:id/manipulate', to: 'images#manipulate'
  resources :images do
    get 'manipulate'
  end

  resources :authors
  resources :topics
  resources :featured_collections
  resources :regions
  resources :cal_standards
  resources :nat_standards

  get '*path', to: redirect('/'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # # The above rule doesn't match the root, so add it
  match '/' => 'errors#error_404', via: :all
end

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="content portlet-0">
          <span>This History Project at UC Davis</span><br />
          <span>One Shields Ave, 163 Kerr Hall, Davis, CA, 95616</span><br />
          <span></span>tel: 530.752.4383<br />fax: 530.752.5655<br />
          <a href="mailto:historyproject@ucdavis.edu" target="_self">historyproject@ucdavis.edu</a>
        </div>
      </div>
      <div class="col-md-3">
        <div class="content portlet-1">
          <div class="column">
            <ul>
              <li><a href="https://historyproject.ucdavis.edu/programs"><span>Programs</span></a></li>
              <li><a href="https://historyproject.ucdavis.edu/resources"><span>Resources</span></a></li>
              <li><a href="https://historyproject.ucdavis.edu/events"><span>Events</span></a></li>
              <li><a href="https://historyproject.ucdavis.edu/about-us"><span>About Us</span></a></li>
            </ul>
          </div>
          <div class="column">
            <ul>
              <li><a href="https://historyproject.ucdavis.edu/about-us/staff"><span>Join Our Team</span></a></li>
              <li><div class="line"></div></li>
              <li><a href="https://historyproject.ucdavis.edu/sitemap"><span>Sitemap</span></a></li>
              <li><a href="https://historyproject.ucdavis.edu/accessibility-info"><span>Accessibility</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="content portlet-2">
          <a href="https://historyproject.ucdavis.edu/front-page" target="_self">
            <img src="https://historyproject.ucdavis.edu/images-and-files/UCDHP_logo_all_White_LA_small.png" alt="UC Davis White Logo Small LA" class="image-inline" title="UC Davis White Logo Small LA" />
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="portal-footer">
  <a href="http://www.ucdavis.edu">Copyright<sup>®</sup></a> by
  <abbr title="Copyright">©</abbr> 2000-2019 by the
  <a href="http://www.ucdavis.edu">The Regents of the University of California, Davis campus. All rights reserved.</a>
</div>

app/views/shared/_header.html.erb
<header id="header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <div class="content portlet-2 pull-left">
          <p>
            <a href="<%= root_url %>"><%= image_tag("Marchand Archive logo - all white.png", :class => "center-block marchand-logo") %></a>
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="content portlet-2 pull-right">
          <p>
            <a title="UC Davis White Logo Small LA" href="https://historyproject.ucdavis.edu/front-page" target="_self">
              <%= image_tag("UCDHP logo White Full - THE LA.png", alt: "UC Davis White Logo Small LA", class: "history-project-logo", title: "UC Davis White Logo Small LA") %>
            </a>
          </p>
        </div>
    </div>
  </div>
</header>

<!-- BREADCRUMB -->
  <ul class="breadcrumb">
    <li>You are here: <a href="https://historyproject.ucdavis.edu/">Home</a></li>
    <li><a href="https://historyproject.ucdavis.edu/resources">Resources</a></li>
    <li><a href="https://marchand.dss.ucdavis.edu/">Marchand Archive</a></li>
    <li class="pull-right">
      <% if session[:cas_user].present? %>
        <a href="/logout">CAS Logout</a>
      <% else %>
        <a href="/login">CAS Login</a>
      <% end %>
    </li>
  </ul>

<%= render 'shared/nav' %>

app/views/shared/_multi_dropdown.html.erb
<!-- f => form_for @image-->
<!-- klass => class to build fields for -->
<!-- member => nested_attribute to build fields_for -->
<!-- collection => collection of objects to render -->

<% title = defined?(klass.readable_class_name) ? klass.readable_class_name : klass.name %>
<% column = "#{klass.name.underscore}_ids".to_sym %>

<div class="col-xs-6">
  <h5><%= title.pluralize %></h5>

  <div class="btn-group" style="width: 100%;">

    <div id="<%= klass.name %>" class="customized-search-group" style="width: calc(100% - 45px);
      min-height: 35px;
      background-color: #fff;
      text-align: left;
      display: inline-block;
      padding: 2px 12px;
      padding-bottom: 5px;
      margin-bottom: 0;
      border: 1px solid #ccc;
      border-radius: 4px;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      float: left;">
    </div>

    <button type="button" class="btn btn-default dropdown-toggle" style="border-left: none; min-height: 35px;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="caret"></span>
      <span class="sr-only">Toggle Dropdown</span>
    </button>

    <div class="dropdown-menu" data-type="menu">
      <div class="select2-search">
        <span class="glyphicon glyphicon-search input-search-icon"></span>
        <input class="dropdown-search" type="text" data-type="search-box" />
      </div>

      <ul class="dropdown-list" data-type="list" data-target="span">
        <%= f.collection_check_boxes column, collection, :id, :title, {}, "data-target-id" => klass.name do |b| %>
        <li>
          <a>
            <div class="customized-checkbox">
              <span> <%= b.text %> </span>
              <%= b.check_box %>
              <% # The block passed is essential to have a label with no text %>
              <%= b.label { " " } %>
            </div>
          </a>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="row">
  <div class="container-fluid">
    <nav class="navbar col-lg-7 col-md-10 col-xs-12 pull-right">
      <button type="button"class="navbar-toggle"data-toggle="collapse" data-target="#navbar-collapse">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <ul class="nav navbar-nav">
            <% if session[:cas_user].present? %>
              <% if admin? %>
                <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">Admin<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a data-toggle="dropdown" class="dropdown-toggle" href="<%= new_image_url %>" class="admin-nav-link">Add New Image</a></li>
                    <li><a data-toggle="dropdown" class="dropdown-toggle" href="#">Add New Lesson</a></li> <%# TODO: add lesson link %>
                    <li><a data-toggle="dropdown" class="dropdown-toggle" href="/admin" class="admin-nav-link">Manage Metadata</a></li>
                  </ul>
                </li>
              <% end %>
            <% end %>
            <li><a href="<%= root_url %>">Image Collections</a></li>
            <li><a href="<%= images_url %>">Browse All Images</a></li>
            <!-- <li><a href="#">Primary Source Sets</a></li> <%# TODO: add primary source sets %> -->
          </ul>
        </ul>
      </div>
    </nav>
  </div>
</div>